config/routes.rb
EmailMarketing::Engine.routes.draw do

  namespace :admin do
    resources :marketing_templates, only: [:index, :show]
    resources :marketing_lists, except: :destroy do
      get "new_csv", to: "marketing_lists#new_csv", as: :new_csv, on: :collection
      post "create_csv", to: "marketing_lists#create_csv", as: :create_csv, on: :collection
    end
    resources :marketing_deliveries, only: [:index, :new, :create]
  end

end

app/controllers/email_marketing/admin/admins_controller.rb
module EmailMarketing
  module Admin
    class AdminsController < ::Admin::AdminsController
      helper EmailMarketing::ApplicationHelper

      def marketing_connection
        ::MarketingConnection::Base.new(api_key: ::MarketingConnection.api_key, api_secret: ::MarketingConnection.api_secret)
      end

      def set_errors(object, errors, overides = {})
        errors.each do |k,v|
          new_k = overides[k.to_sym]
          k = new_k if new_k
          object.errors.add(k.to_sym, v.first)
        end
      end

    end
  end
end

app/controllers/email_marketing/admin/marketing_deliveries_controller.rb
module EmailMarketing
  module Admin
    class MarketingDeliveriesController < AdminsController
      before_action :set_values, only: [:new, :create]

      def index
        response = marketing_connection.deliveries.list
        @deliveries = response["deliveries"]
      end

      def new
        @delivery = Delivery.new
      end

      def create
        got_params = params.require(:admin_delivery).permit(:name, :domain, :gun_name, :template_id, :from, :list_id)
        @delivery = Delivery.new(got_params)
        @delivery.domain = @domains.first["name"] if @domains.count == 1
        response = @delivery.submit
        errors = response["errors"]
        if errors
          set_errors(@delivery, errors, {template: "template_id", list: "list_id"})
          render "new"
        else
          redirect_to admin_marketing_deliveries_path, flash: {success: "Enviado"}
        end
      end

      private

        def set_values
          response = marketing_connection.lists.list
          @lists = response["lists"]
          response = marketing_connection.templates.list
          @templates = response["templates"]
          response = marketing_connection.guns.list
          guns = response["guns"]
          mailgun = Mailgun::Base.new(api_key: guns.first["key"])
          @domains = mailgun.domains.list
        end

    end


    class Delivery < AdminsController
      include ActiveModel::Model
      attr_accessor :name, :template_id, :from, :list_id, :domain, :gun, :gun_name
      def submit
        json = JSON(self.to_json)
        parameters =  {delivery: json}
        response = marketing_connection.deliveries.create(parameters)
      end
    end

  end
end

app/controllers/email_marketing/admin/marketing_lists_controller.rb
module EmailMarketing
  module Admin
    class MarketingListsController < AdminsController

      def index
        response = marketing_connection.lists.list
        @lists = response["lists"]
      end

      def show
        response = marketing_connection.lists.find(params[:id])
        @emails = response["emails"]
      end

      def new
        @list = List.new
      end

      def create
        got_params = params.require(:admin_list).permit(:name, :list_emails)
        @list = List.new(got_params)
#        if @list.valid?
          response = @list.submit
          errors = response["errors"]
          if errors
            set_errors(@list, errors)
            render "new"
          else
            redirect_to admin_marketing_lists_path, flash: {success: "Lista creada exitosamente"}
          end
#        else
#          render "new"
#        end
      end

      def new_csv
        @list = List.new
      end


      def create_csv
        got_params = params.require(:admin_list).permit(:name, :csv_file)
        @list = List.new(got_params)
        response = @list.submit_csv
        errors = response["errors"]
        if errors
          set_errors(@list, errors)
          render "new_csv"
        else
          redirect_to admin_marketing_lists_path, flash: {success: response["notification"]}
        end
      end



    end


    class List < AdminsController
      include ActiveModel::Model
      attr_accessor :name, :list_emails, :csv_file

      #validates :name, presence: true
      #validates :list_emails, presence: true

      def submit
        json = JSON(self.to_json)
        parameters =  {list: json}
        response = marketing_connection.lists.create(parameters)
      end

      def submit_csv
        attrs = {
          name: self.name,
          csv_file: self.csv_file
        }
        response = marketing_connection.lists.create_csv(list: attrs)
      end




    end

  end
end

app/controllers/email_marketing/admin/marketing_templates_controller.rb
module EmailMarketing
  module Admin
    class MarketingTemplatesController < AdminsController
      layout :get_layout
      def index
        response = marketing_connection.templates.list
        @templates = response["templates"]
      end

      def show
        response = marketing_connection.templates.find(params[:id])
        @template = response
      end


      private
        def get_layout
          "blank" if action_name == "show"
        end

    end
  end
end

app/controllers/email_marketing/application_controller.rb
module EmailMarketing
  class ApplicationController #< #ActionController::Base#::Admin::AdminsController
  end
end

app/helpers/email_marketing/application_helper.rb
module EmailMarketing
  module ApplicationHelper

    def method_missing(method, *args, &block)
      if (method.to_s.end_with?('_path') || method.to_s.end_with?('_url')) && main_app.respond_to?(method)
        main_app.send(method, *args)
      else
        super
      end
    end

  end
end

app/views/email_marketing/admin/marketing_deliveries/index.html.haml
=render "email_marketing/admin/shared/menu"
%h1.page-header Envíos

=link_to "Nuevo", new_admin_marketing_delivery_path, class: "btn btn-primary"
%table.table.table-striped.table-hover
  %thead
    %tr
      %th Nombre
  %tbody
    -@deliveries.each do |delivery|
      %tr
        %td=delivery["name"]

app/views/email_marketing/admin/marketing_deliveries/new.html.haml
%h1.page-header Nuevo envio

=simple_form_for @delivery, url: admin_marketing_deliveries_path do |f|
  =@delivery.errors.inspect
  .row
    .col-md-6
      = f.input :name
  .row
    .col-md-6
      = f.input :domain, collection: @domains.map{|h| h["name"]} if @domains.count > 1
      =# f.input :gun_name, as: :string
    .col-md-6
      = f.input :from
  .row
    .col-md-6
      = f.input :template_id, collection:  @templates.map{|h| [h["name"], h["id"]]}
    .col-md-6
      = f.input :list_id, collection: @lists.map{|h| [h["name"], h["id"]]}
  =f.submit "Guardar", class: "btn btn-primary"

app/views/email_marketing/admin/marketing_lists/index.html.haml
=render "email_marketing/admin/shared/menu"
%h1.page-header Listas
=link_to "Nueva lista", new_admin_marketing_list_path, class: "btn btn-primary pull-right"
=link_to "Nueva lista CSV", new_csv_admin_marketing_lists_path, class: "btn btn-primary pull-right"

%table.table.table-striped.table-hover
  %thead
    %tr
      %th Nombre
  %tbody
    -@lists.each do |list|
      %tr
        %td=link_to list["name"], admin_marketing_list_path(list["slug"])

app/views/email_marketing/admin/marketing_lists/new.html.haml
=simple_form_for @list, url: admin_marketing_lists_path do |f|
  =f.input :name
  =f.input :list_emails, as: :text
  =f.submit "Guardar", class: "btn btn-primary"

app/views/email_marketing/admin/marketing_lists/new_csv.html.haml
=simple_form_for @list, url: create_csv_admin_marketing_lists_path do |f|
  =f.input :name
  =f.input :csv_file, as: :file
  =f.submit "Guardar", class: "btn btn-primary"

app/views/email_marketing/admin/marketing_lists/show.html.haml
=render "email_marketing/admin/shared/menu"
%h1.page-header Lista - #{params[:id]}
%table.table.table-striped.table-hover
  %thead
    %tr
      %th Email
  %tbody
    -@emails.each do |email|
      %tr
        %td= email["email"]

app/views/email_marketing/admin/marketing_templates/index.html.haml
=render "email_marketing/admin/shared/menu"
%h1.page-header Templates
%table.table.table-striped.table-hover
  %thead
    %tr
      %th Nombre
  %tbody
    -@templates.each do |template|
      %tr
        %td=link_to template["name"], admin_marketing_template_path(template["slug"])

app/views/email_marketing/admin/marketing_templates/show.html.haml
=@template["content"].html_safe

app/views/email_marketing/admin/shared/_menu.html.haml
%ul.nav.nav-pills
  %li.admin_marketing_lists= link_to "Listas", admin_marketing_lists_path
  %li.admin_marketing_templates= link_to "Templates", admin_marketing_templates_path
  %li.admin_marketing_deliveries= link_to "Envios", admin_marketing_deliveries_path



:coffeescript
  $ ->
    class_name = ".admin_#{controller_name}"
    console.log class_name
    $(class_name).addClass("active")

app/views/layouts/blank.html.haml
=yield